namespace RavensPort.Core.Models;

public sealed class AppSettings
{
    public int ListenPort { get; set; } = 5559;

    /// <summary>
    /// Master switch for the MCP funnel endpoints under /mcp. Off by default: the funnel lets a
    /// caller reach several upstreams (and their attached OAuth grants) through one path, so it
    /// stays dark until the user asks for it rather than appearing on upgrade.
    /// </summary>
    public bool McpFunnelEnabled { get; set; }

    /// <summary>
    /// If true, the proxy and funnel routes require a client certificate for authentication.
    /// Kestrel binds to https://127.0.0.1 and enforces client certificate validation.
    /// </summary>
    public bool MtlsEnabled { get; set; }

    /// <summary>
    /// The Base64 encoded PFX string for the mTLS client certificate generated by the UI.
    /// </summary>
    public string MtlsClientCertificatePfx { get; set; } = "";

    /// <summary>
    /// The password <see cref="MtlsClientCertificatePfx"/> is encrypted with, when the user chose
    /// one on the Settings tab. Empty means the certificate carries
    /// <see cref="Proxy.MtlsCertificateFactory.DefaultPfxPassword"/> — which is the case for every
    /// store written before this field existed, and for the certificates the app mints for itself
    /// when the switch is turned on with nothing stored and there is nobody to ask.
    ///
    /// It lives here because the app has to re-read its own certificate unattended at every start,
    /// so a password it cannot recover is a password that locks the proxy out of its own listener.
    /// The vault this is written to is the same one holding the OAuth refresh tokens; a password
    /// stored beside the file it opens buys nothing on top of that, which is why the exported copy
    /// is the credential and the password is only there to stop Windows and curl refusing a PFX
    /// with no password at all.
    /// </summary>
    public string MtlsClientCertificatePassword { get; set; } = "";

    // There is deliberately no proxy-wide API key here. Authentication is per endpoint: every
    // route and every funnel carries its own <see cref="ProxyKey"/>, so a key leaked from one
    // client cannot spend the OAuth grant attached to a different route, and revoking one client
    // is a single-endpoint operation rather than a re-key of everything.
}
