using System.Windows;
using RavensPort.Core.Vault;

// UseWindowsForms is on for the tray icon, so both frameworks' Application types are in scope.
using Application = System.Windows.Application;

namespace RavensPort.App.Views;

/// <summary>
/// The consent step in front of every Windows Hello prompt RavensPort raises. See the comment in
/// the XAML for why it has no exceptions.
/// </summary>
public partial class HelloConsentWindow : Window
{
    /// <summary>
    /// The Hello-backed operation. It must signal failure by throwing — a method that catches its
    /// own errors and returns false reports success here, which is how a session key that was never
    /// stored once looked to the user like one that was.
    /// </summary>
    private readonly Func<Task> _action;

    /// <summary>True once the Hello-backed operation actually succeeded.</summary>
    public bool Confirmed { get; private set; }

    private HelloConsentWindow(string heading, string body, string detail, string confirmText, Func<Task> action)
    {
        _action = action;

        InitializeComponent();

        HeadingText.Text = heading;
        BodyText.Text = body;
        DetailText.Text = detail;
        ConfirmButton.Content = confirmText;
    }

    /// <summary>
    /// Asks before unlocking the session with Hello.
    /// </summary>
    public static bool RequestUnlock(Func<Task> unlockAsync) => Show(new HelloConsentWindow(
        "Unlock RavensPort",
        "RavensPort wants to ask Windows Hello to unlock its Proton Pass session on this PC, so the "
        + "proxy can start.",
        "Your session key is held in Windows Credential Manager, encrypted so that only a Windows Hello "
        + "gesture on this PC can decrypt it. The gesture is not a check RavensPort could skip — the key "
        + "it produces is what performs the decryption. Nothing is sent to Proton, nothing is read from "
        + "your vault by this step, and your Proton password is not involved.",
        "Unlock with Windows Hello",
        unlockAsync));

    /// <summary>
    /// Asks before creating the session key — which happens before the Proton sign-in, not after
    /// it. Declining here means no key and no sign-in, which is the point: there is then nothing
    /// left on this PC that only a lost key could open.
    /// </summary>
    public static bool RequestSetup(Func<Task> prepareAsync) => Show(new HelloConsentWindow(
        "Protect this session with Windows Hello",
        "Before signing in to Proton Pass, RavensPort will create a session key and store it in "
        + "Windows Credential Manager, encrypted so that only Windows Hello can bring it back.",
        "The key is generated by RavensPort, never displayed, never typed, and never copied to the "
        + "clipboard — it goes straight into Credential Manager encrypted, and from there only into the "
        + "Proton Pass CLI. It is not your Proton password and Proton never receives it. Cancel and "
        + "nothing is created and no sign-in happens.",
        "Continue with Windows Hello",
        prepareAsync));

    private static bool Show(HelloConsentWindow window)
    {
        // Owned by the main window when there is a visible one, so it centres on it and cannot be
        // lost behind it. At startup there is none — which is the case this window exists to cover.
        var owner = Application.Current?.MainWindow;
        if (owner is { IsVisible: true } && !ReferenceEquals(owner, window)) window.Owner = owner;

        window.ShowDialog();
        return window.Confirmed;
    }

    private async void ConfirmButton_Click(object sender, RoutedEventArgs e)
    {
        ConfirmButton.IsEnabled = false;
        CancelButton.IsEnabled = false;

        Report("Waiting for Windows Hello…", isError: false);

        try
        {
            await _action();

            Confirmed = true;
            Close();
        }
        catch (VaultCliException ex)
        {
            // Cancelled at the Hello prompt, locked out after too many attempts, or a stored key
            // that no longer opens. All of them leave pasting the key as the way through, and the
            // message already says so — so this window stays open to be retried or dismissed.
            Report(ex.Message, isError: true);
        }
        catch (Exception ex)
        {
            Report($"Windows Hello failed: {ex.Message}", isError: true);
        }
        finally
        {
            ConfirmButton.IsEnabled = true;
            CancelButton.IsEnabled = true;
        }
    }

    private void CancelButton_Click(object sender, RoutedEventArgs e) => Close();

    private void Report(string message, bool isError)
    {
        StatusText.Text = message;
        StatusText.Visibility = Visibility.Visible;
        StatusText.Foreground = isError
            ? (System.Windows.Media.Brush)FindResource("ErrorBrush")
            : (System.Windows.Media.Brush)FindResource("MutedTextBrush");
    }
}
