using System.Windows;
using RavensPort.Core.Vault;

// UseWindowsForms is on for the tray icon, so both frameworks' Application types are in scope.
using Application = System.Windows.Application;

namespace RavensPort.App.Views;

/// <summary>
/// The consent step in front of every Windows Hello prompt RavensPort raises. See the comment in
/// the XAML for why it has no exceptions.
/// </summary>
public partial class HelloConsentWindow : Window
{
    /// <summary>
    /// The Hello-backed operation. It must signal failure by throwing — a method that catches its
    /// own errors and returns false reports success here, which is how a session key that was never
    /// stored once looked to the user like one that was.
    /// </summary>
    private readonly Func<Task> _action;

    /// <summary>True once the Hello-backed operation actually succeeded.</summary>
    public bool Confirmed { get; private set; }

    private HelloConsentWindow(
        string heading,
        string body,
        string detail,
        string confirmText,
        Func<Task> action,
        string vendorLogo = "/Assets/proton-pass-logo.png")
    {
        _action = action;

        InitializeComponent();

        HeadingText.Text = heading;
        BodyText.Text = body;
        DetailText.Text = detail;
        ConfirmButton.Content = confirmText;
        VendorLogo.Source = new System.Windows.Media.Imaging.BitmapImage(
            new Uri(vendorLogo, UriKind.Relative));

        // Re-anchored on every size change, not just once at load. The window is SizeToContent, so
        // it grows when Report() reveals the status line — anchored only at startup, the bottom
        // edge would then push down past the taskbar and take the buttons with it.
        SizeChanged += (_, _) => AnchorAboveTray();
    }

    /// <summary>
    /// Puts the window in the bottom-right corner, above the tray.
    ///
    /// Centred, it landed exactly on top of the Windows Hello prompt it exists to explain — which
    /// defeats the point of showing it at all, since the user cannot read what they are approving
    /// while approving it. Down here both are visible at once, and it sits beside the tray icon
    /// that represents the app doing the asking.
    ///
    /// <see cref="SystemParameters.WorkArea"/> rather than the screen bounds, so this lands above
    /// the taskbar wherever the user keeps it — including left or top, where a hard-coded corner
    /// would be wrong. It is in device-independent units already, so it survives display scaling
    /// without a manual DPI conversion.
    /// </summary>
    private void AnchorAboveTray()
    {
        const double margin = 12;

        var work = SystemParameters.WorkArea;

        // ActualWidth is 0 until the first layout pass; Width is fixed in XAML, so it is the
        // reliable one to subtract before then.
        var width = ActualWidth > 0 ? ActualWidth : Width;
        var height = ActualHeight > 0 ? ActualHeight : MinHeight;

        Left = work.Right - width - margin;

        // Clamped to the top of the work area: a window taller than the screen would otherwise be
        // positioned at a negative Top, hiding its heading off the top edge rather than its
        // buttons off the bottom.
        Top = Math.Max(work.Top, work.Bottom - height - margin);
    }

    /// <summary>
    /// Asks before unlocking the session with Hello.
    /// </summary>
    public static bool RequestUnlock(Func<Task> unlockAsync) => Show(new HelloConsentWindow(
        "Unlock RavensPort",
        "RavensPort wants to ask Windows Hello to unlock its Proton Pass session on this PC, so the "
        + "proxy can start.",
        "Your session key is held in Windows Credential Manager, encrypted so that only a Windows Hello "
        + "gesture on this PC can decrypt it. The gesture is not a check RavensPort could skip — the key "
        + "it produces is what performs the decryption. Nothing is sent to Proton, nothing is read from "
        + "your vault by this step, and your Proton password is not involved.",
        "Unlock with Windows Hello",
        unlockAsync));

    /// <summary>
    /// Asks before creating the session key — which happens before the Proton sign-in, not after
    /// it. Declining here means no key and no sign-in, which is the point: there is then nothing
    /// left on this PC that only a lost key could open.
    /// </summary>
    public static bool RequestSetup(Func<Task> prepareAsync) => Show(new HelloConsentWindow(
        "Protect this session with Windows Hello",
        "Before signing in to Proton Pass, RavensPort will create a session key and store it in "
        + "Windows Credential Manager, encrypted so that only Windows Hello can bring it back.",
        "The key is generated by RavensPort, never displayed, never typed, and never copied to the "
        + "clipboard — it goes straight into Credential Manager encrypted, and from there only into the "
        + "Proton Pass CLI. It is not your Proton password and Proton never receives it. Cancel and "
        + "nothing is created and no sign-in happens.",
        "Continue with Windows Hello",
        prepareAsync));

    private const string OnePasswordLogo = "/Assets/onepassword-logo.png";

    /// <summary>
    /// Asks before keeping a 1Password service-account token between runs.
    ///
    /// Its own consent step, and deliberately not folded into a checkbox that saves silently. Up to
    /// this point the token has lived only in memory and the app has said so plainly; storing one is
    /// a change to that promise, and the user should be the one making it, having read what it does
    /// and does not protect.
    /// </summary>
    public static bool RequestTokenSave(Func<Task> protectAsync) => Show(new HelloConsentWindow(
        "Keep this token on this PC?",
        "RavensPort will store your 1Password service account token in Windows Credential Manager, "
        + "encrypted so that only a Windows Hello gesture on this PC can bring it back.",
        "The token is encrypted with a key that is not stored anywhere: it is derived from your Hello "
        + "signature each time, so the saved bytes open only to a gesture on this PC. It is never "
        + "written in plain text and never leaves this machine. Anyone who can already sign in as you "
        + "here could still ask for that gesture, so only do this on a PC you own and trust — and "
        + "remember the token stays valid until you rotate it in 1Password. Cancel and nothing is "
        + "saved; you will simply paste it again next time.",
        "Save with Windows Hello",
        protectAsync,
        OnePasswordLogo));

    /// <summary>
    /// Asks before bringing a saved token back at startup.
    /// </summary>
    public static bool RequestTokenUnlock(Func<Task> unlockAsync) => Show(new HelloConsentWindow(
        "Unlock your 1Password token",
        "RavensPort wants to ask Windows Hello to unlock the saved 1Password service account token, "
        + "so it can connect without you pasting it again.",
        "The token is held in Windows Credential Manager, encrypted so that only a Windows Hello "
        + "gesture on this PC can decrypt it. The gesture is not a check RavensPort could skip — the "
        + "key it produces is what performs the decryption. Cancel and nothing is decrypted; you can "
        + "paste a token by hand instead, or forget the saved one on the Settings tab.",
        "Unlock with Windows Hello",
        unlockAsync,
        OnePasswordLogo));

    private static bool Show(HelloConsentWindow window)
    {
        // Owned by the main window when there is a visible one, so it centres on it and cannot be
        // lost behind it. At startup there is none — which is the case this window exists to cover.
        var owner = Application.Current?.MainWindow;
        if (owner is { IsVisible: true } && !ReferenceEquals(owner, window)) window.Owner = owner;

        window.ShowDialog();
        return window.Confirmed;
    }

    private async void ConfirmButton_Click(object sender, RoutedEventArgs e)
    {
        ConfirmButton.IsEnabled = false;
        CancelButton.IsEnabled = false;

        Report("Waiting for Windows Hello…", isError: false);

        try
        {
            await _action();

            Confirmed = true;
            Close();
        }
        catch (VaultCliException ex)
        {
            // Cancelled at the Hello prompt, locked out after too many attempts, or a stored key
            // that no longer opens. All of them leave pasting the key as the way through, and the
            // message already says so — so this window stays open to be retried or dismissed.
            Report(ex.Message, isError: true);
        }
        catch (Exception ex)
        {
            Report($"Windows Hello failed: {ex.Message}", isError: true);
        }
        finally
        {
            ConfirmButton.IsEnabled = true;
            CancelButton.IsEnabled = true;
        }
    }

    private void CancelButton_Click(object sender, RoutedEventArgs e) => Close();

    private void Report(string message, bool isError)
    {
        StatusText.Text = message;
        StatusText.Visibility = Visibility.Visible;
        StatusText.Foreground = isError
            ? (System.Windows.Media.Brush)FindResource("ErrorBrush")
            : (System.Windows.Media.Brush)FindResource("MutedTextBrush");
    }
}
